# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171012_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='no link available', max_length=120),
        ),
    ]
